export const statesByCountry = {
  us: [
    { value: "al", label: "Alabama" },
    { value: "ak", label: "Alaska" },
    { value: "az", label: "Arizona" },
    { value: "ar", label: "Arkansas" },
    { value: "ca", label: "California" },
    { value: "co", label: "Colorado" },
    { value: "ct", label: "Connecticut" },
    { value: "de", label: "Delaware" },
    { value: "fl", label: "Florida" },
    { value: "ga", label: "Georgia" },
    { value: "hi", label: "Hawaii" },
    { value: "id", label: "Idaho" },
    { value: "il", label: "Illinois" },
    { value: "in", label: "Indiana" },
    { value: "ia", label: "Iowa" },
    { value: "ks", label: "Kansas" },
    { value: "ky", label: "Kentucky" },
    { value: "la", label: "Louisiana" },
    { value: "me", label: "Maine" },
    { value: "md", label: "Maryland" },
    { value: "ma", label: "Massachusetts" },
    { value: "mi", label: "Michigan" },
    { value: "mn", label: "Minnesota" },
    { value: "ms", label: "Mississippi" },
    { value: "mo", label: "Missouri" },
    { value: "mt", label: "Montana" },
    { value: "ne", label: "Nebraska" },
    { value: "nv", label: "Nevada" },
    { value: "nh", label: "New Hampshire" },
    { value: "nj", label: "New Jersey" },
    { value: "nm", label: "New Mexico" },
    { value: "ny", label: "New York" },
    { value: "nc", label: "North Carolina" },
    { value: "nd", label: "North Dakota" },
    { value: "oh", label: "Ohio" },
    { value: "ok", label: "Oklahoma" },
    { value: "or", label: "Oregon" },
    { value: "pa", label: "Pennsylvania" },
    { value: "ri", label: "Rhode Island" },
    { value: "sc", label: "South Carolina" },
    { value: "sd", label: "South Dakota" },
    { value: "tn", label: "Tennessee" },
    { value: "tx", label: "Texas" },
    { value: "ut", label: "Utah" },
    { value: "vt", label: "Vermont" },
    { value: "va", label: "Virginia" },
    { value: "wa", label: "Washington" },
    { value: "wv", label: "West Virginia" },
    { value: "wi", label: "Wisconsin" },
    { value: "wy", label: "Wyoming" },
    { value: "dc", label: "District of Columbia" }
  ],
  ca: [
    { value: "ab", label: "Alberta" },
    { value: "bc", label: "British Columbia" },
    { value: "mb", label: "Manitoba" },
    { value: "nb", label: "New Brunswick" },
    { value: "nl", label: "Newfoundland and Labrador" },
    { value: "ns", label: "Nova Scotia" },
    { value: "nt", label: "Northwest Territories" },
    { value: "nu", label: "Nunavut" },
    { value: "on", label: "Ontario" },
    { value: "pe", label: "Prince Edward Island" },
    { value: "qc", label: "Quebec" },
    { value: "sk", label: "Saskatchewan" },
    { value: "yt", label: "Yukon" }
  ],
  gb: [
    { value: "eng", label: "England" },
    { value: "sct", label: "Scotland" },
    { value: "wls", label: "Wales" },
    { value: "nir", label: "Northern Ireland" }
  ],
  fr: [
    { value: "ara", label: "Auvergne-Rhône-Alpes" },
    { value: "bfc", label: "Bourgogne-Franche-Comté" },
    { value: "bre", label: "Bretagne" },
    { value: "cvl", label: "Centre-Val de Loire" },
    { value: "cor", label: "Corse" },
    { value: "ges", label: "Grand Est" },
    { value: "hdf", label: "Hauts-de-France" },
    { value: "idf", label: "Île-de-France" },
    { value: "nor", label: "Normandie" },
    { value: "naq", label: "Nouvelle-Aquitaine" },
    { value: "occ", label: "Occitanie" },
    { value: "pdl", label: "Pays de la Loire" },
    { value: "pac", label: "Provence-Alpes-Côte d'Azur" }
  ],
  de: [
    { value: "bw", label: "Baden-Württemberg" },
    { value: "by", label: "Bayern" },
    { value: "be", label: "Berlin" },
    { value: "bb", label: "Brandenburg" },
    { value: "hb", label: "Bremen" },
    { value: "hh", label: "Hamburg" },
    { value: "he", label: "Hessen" },
    { value: "mv", label: "Mecklenburg-Vorpommern" },
    { value: "ni", label: "Niedersachsen" },
    { value: "nw", label: "Nordrhein-Westfalen" },
    { value: "rp", label: "Rheinland-Pfalz" },
    { value: "sl", label: "Saarland" },
    { value: "sn", label: "Sachsen" },
    { value: "st", label: "Sachsen-Anhalt" },
    { value: "sh", label: "Schleswig-Holstein" },
    { value: "th", label: "Thüringen" }
  ],
  it: [
    { value: "abr", label: "Abruzzo" },
    { value: "bas", label: "Basilicata" },
    { value: "cal", label: "Calabria" },
    { value: "cam", label: "Campania" },
    { value: "emr", label: "Emilia-Romagna" },
    { value: "fvg", label: "Friuli Venezia Giulia" },
    { value: "laz", label: "Lazio" },
    { value: "lig", label: "Liguria" },
    { value: "lom", label: "Lombardia" },
    { value: "mar", label: "Marche" },
    { value: "mol", label: "Molise" },
    { value: "pie", label: "Piemonte" },
    { value: "pug", label: "Puglia" },
    { value: "sar", label: "Sardegna" },
    { value: "sic", label: "Sicilia" },
    { value: "tos", label: "Toscana" },
    { value: "taa", label: "Trentino-Alto Adige" },
    { value: "umb", label: "Umbria" },
    { value: "vda", label: "Valle d'Aosta" },
    { value: "ven", label: "Veneto" }
  ],
  es: [
    { value: "and", label: "Andalucía" },
    { value: "ara", label: "Aragón" },
    { value: "ast", label: "Asturias" },
    { value: "bal", label: "Baleares" },
    { value: "can", label: "Canarias" },
    { value: "cnt", label: "Cantabria" },
    { value: "clm", label: "Castilla-La Mancha" },
    { value: "cyl", label: "Castilla y León" },
    { value: "cat", label: "Cataluña" },
    { value: "ceu", label: "Ceuta" },
    { value: "ext", label: "Extremadura" },
    { value: "gal", label: "Galicia" },
    { value: "mad", label: "Madrid" },
    { value: "mel", label: "Melilla" },
    { value: "mur", label: "Murcia" },
    { value: "nav", label: "Navarra" },
    { value: "pva", label: "País Vasco" },
    { value: "rio", label: "La Rioja" },
    { value: "val", label: "Comunidad Valenciana" }
  ],
  au: [
    { value: "act", label: "Australian Capital Territory" },
    { value: "nsw", label: "New South Wales" },
    { value: "nt", label: "Northern Territory" },
    { value: "qld", label: "Queensland" },
    { value: "sa", label: "South Australia" },
    { value: "tas", label: "Tasmania" },
    { value: "vic", label: "Victoria" },
    { value: "wa", label: "Western Australia" }
  ],
  nz: [
    { value: "auk", label: "Auckland" },
    { value: "bop", label: "Bay of Plenty" },
    { value: "can", label: "Canterbury" },
    { value: "gis", label: "Gisborne" },
    { value: "hkb", label: "Hawke's Bay" },
    { value: "mwt", label: "Manawatu-Whanganui" },
    { value: "mbh", label: "Marlborough" },
    { value: "nsn", label: "Nelson" },
    { value: "ntl", label: "Northland" },
    { value: "ota", label: "Otago" },
    { value: "stl", label: "Southland" },
    { value: "tas", label: "Tasman" },
    { value: "tki", label: "Taranaki" },
    { value: "wko", label: "Waikato" },
    { value: "wgn", label: "Wellington" },
    { value: "wtc", label: "West Coast" }
  ],
  jp: [
    { value: "hok", label: "Hokkaido" },
    { value: "aom", label: "Aomori" },
    { value: "iwt", label: "Iwate" },
    { value: "myg", label: "Miyagi" },
    { value: "akt", label: "Akita" },
    { value: "ymg", label: "Yamagata" },
    { value: "fks", label: "Fukushima" },
    { value: "ibr", label: "Ibaraki" },
    { value: "tcg", label: "Tochigi" },
    { value: "gnm", label: "Gunma" },
    { value: "stm", label: "Saitama" },
    { value: "chb", label: "Chiba" },
    { value: "tky", label: "Tokyo" },
    { value: "kng", label: "Kanagawa" },
    { value: "nig", label: "Niigata" },
    { value: "tym", label: "Toyama" },
    { value: "isk", label: "Ishikawa" },
    { value: "fki", label: "Fukui" },
    { value: "ymn", label: "Yamanashi" },
    { value: "ngn", label: "Nagano" },
    { value: "gif", label: "Gifu" },
    { value: "szk", label: "Shizuoka" },
    { value: "aic", label: "Aichi" },
    { value: "mie", label: "Mie" },
    { value: "sig", label: "Shiga" },
    { value: "kyt", label: "Kyoto" },
    { value: "osk", label: "Osaka" },
    { value: "hyo", label: "Hyogo" },
    { value: "nar", label: "Nara" },
    { value: "wky", label: "Wakayama" },
    { value: "ttr", label: "Tottori" },
    { value: "smn", label: "Shimane" },
    { value: "oky", label: "Okayama" },
    { value: "hrs", label: "Hiroshima" },
    { value: "ymg", label: "Yamaguchi" },
    { value: "tks", label: "Tokushima" },
    { value: "kgw", label: "Kagawa" },
    { value: "ehm", label: "Ehime" },
    { value: "koc", label: "Kochi" },
    { value: "fko", label: "Fukuoka" },
    { value: "sag", label: "Saga" },
    { value: "ngs", label: "Nagasaki" },
    { value: "kmt", label: "Kumamoto" },
    { value: "oit", label: "Oita" },
    { value: "myz", label: "Miyazaki" },
    { value: "kgs", label: "Kagoshima" },
    { value: "okn", label: "Okinawa" }
  ],
  kr: [
    { value: "seo", label: "Seoul" },
    { value: "bus", label: "Busan" },
    { value: "dae", label: "Daegu" },
    { value: "inc", label: "Incheon" },
    { value: "gwj", label: "Gwangju" },
    { value: "daj", label: "Daejeon" },
    { value: "ulp", label: "Ulsan" },
    { value: "sej", label: "Sejong" },
    { value: "ggi", label: "Gyeonggi" },
    { value: "gww", label: "Gangwon" },
    { value: "cbb", label: "Chungbuk" },
    { value: "cbn", label: "Chungnam" },
    { value: "jlb", label: "Jeonbuk" },
    { value: "jln", label: "Jeonnam" },
    { value: "gsb", label: "Gyeongbuk" },
    { value: "gsn", label: "Gyeongnam" },
    { value: "jju", label: "Jeju" }
  ],
  in: [
    { value: "ap", label: "Andhra Pradesh" },
    { value: "ar", label: "Arunachal Pradesh" },
    { value: "as", label: "Assam" },
    { value: "br", label: "Bihar" },
    { value: "ct", label: "Chhattisgarh" },
    { value: "ga", label: "Goa" },
    { value: "gj", label: "Gujarat" },
    { value: "hr", label: "Haryana" },
    { value: "hp", label: "Himachal Pradesh" },
    { value: "jk", label: "Jammu and Kashmir" },
    { value: "jh", label: "Jharkhand" },
    { value: "ka", label: "Karnataka" },
    { value: "kl", label: "Kerala" },
    { value: "mp", label: "Madhya Pradesh" },
    { value: "mh", label: "Maharashtra" },
    { value: "mn", label: "Manipur" },
    { value: "ml", label: "Meghalaya" },
    { value: "mz", label: "Mizoram" },
    { value: "nl", label: "Nagaland" },
    { value: "or", label: "Odisha" },
    { value: "pb", label: "Punjab" },
    { value: "rj", label: "Rajasthan" },
    { value: "sk", label: "Sikkim" },
    { value: "tn", label: "Tamil Nadu" },
    { value: "tg", label: "Telangana" },
    { value: "tr", label: "Tripura" },
    { value: "up", label: "Uttar Pradesh" },
    { value: "ut", label: "Uttarakhand" },
    { value: "wb", label: "West Bengal" }
  ],
  br: [
    { value: "ac", label: "Acre" },
    { value: "al", label: "Alagoas" },
    { value: "ap", label: "Amapá" },
    { value: "am", label: "Amazonas" },
    { value: "ba", label: "Bahia" },
    { value: "ce", label: "Ceará" },
    { value: "df", label: "Distrito Federal" },
    { value: "es", label: "Espírito Santo" },
    { value: "go", label: "Goiás" },
    { value: "ma", label: "Maranhão" },
    { value: "mt", label: "Mato Grosso" },
    { value: "ms", label: "Mato Grosso do Sul" },
    { value: "mg", label: "Minas Gerais" },
    { value: "pa", label: "Pará" },
    { value: "pb", label: "Paraíba" },
    { value: "pr", label: "Paraná" },
    { value: "pe", label: "Pernambuco" },
    { value: "pi", label: "Piauí" },
    { value: "rj", label: "Rio de Janeiro" },
    { value: "rn", label: "Rio Grande do Norte" },
    { value: "rs", label: "Rio Grande do Sul" },
    { value: "ro", label: "Rondônia" },
    { value: "rr", label: "Roraima" },
    { value: "sc", label: "Santa Catarina" },
    { value: "sp", label: "São Paulo" },
    { value: "se", label: "Sergipe" },
    { value: "to", label: "Tocantins" }
  ],
  mx: [
    { value: "agu", label: "Aguascalientes" },
    { value: "bcn", label: "Baja California" },
    { value: "bcs", label: "Baja California Sur" },
    { value: "cam", label: "Campeche" },
    { value: "chp", label: "Chiapas" },
    { value: "chh", label: "Chihuahua" },
    { value: "cmx", label: "Ciudad de México" },
    { value: "coa", label: "Coahuila" },
    { value: "col", label: "Colima" },
    { value: "dur", label: "Durango" },
    { value: "gua", label: "Guanajuato" },
    { value: "gro", label: "Guerrero" },
    { value: "hid", label: "Hidalgo" },
    { value: "jal", label: "Jalisco" },
    { value: "mex", label: "México" },
    { value: "mic", label: "Michoacán" },
    { value: "mor", label: "Morelos" },
    { value: "nay", label: "Nayarit" },
    { value: "nle", label: "Nuevo León" },
    { value: "oax", label: "Oaxaca" },
    { value: "pue", label: "Puebla" },
    { value: "que", label: "Querétaro" },
    { value: "roo", label: "Quintana Roo" },
    { value: "slp", label: "San Luis Potosí" },
    { value: "sin", label: "Sinaloa" },
    { value: "son", label: "Sonora" },
    { value: "tab", label: "Tabasco" },
    { value: "tam", label: "Tamaulipas" },
    { value: "tla", label: "Tlaxcala" },
    { value: "ver", label: "Veracruz" },
    { value: "yuc", label: "Yucatán" },
    { value: "zac", label: "Zacatecas" }
  ],
  za: [
    { value: "ec", label: "Eastern Cape" },
    { value: "fs", label: "Free State" },
    { value: "gt", label: "Gauteng" },
    { value: "kzn", label: "KwaZulu-Natal" },
    { value: "lp", label: "Limpopo" },
    { value: "mp", label: "Mpumalanga" },
    { value: "nw", label: "North West" },
    { value: "nc", label: "Northern Cape" },
    { value: "wc", label: "Western Cape" }
  ],
  cn: [
    { value: "bj", label: "Beijing" },
    { value: "tj", label: "Tianjin" },
    { value: "he", label: "Hebei" },
    { value: "sx", label: "Shanxi" },
    { value: "nm", label: "Inner Mongolia" },
    { value: "ln", label: "Liaoning" },
    { value: "jl", label: "Jilin" },
    { value: "hl", label: "Heilongjiang" },
    { value: "sh", label: "Shanghai" },
    { value: "js", label: "Jiangsu" },
    { value: "zj", label: "Zhejiang" },
    { value: "ah", label: "Anhui" },
    { value: "fj", label: "Fujian" },
    { value: "jx", label: "Jiangxi" },
    { value: "sd", label: "Shandong" },
    { value: "ha", label: "Henan" },
    { value: "hb", label: "Hubei" },
    { value: "hn", label: "Hunan" },
    { value: "gd", label: "Guangdong" },
    { value: "gx", label: "Guangxi" },
    { value: "hi", label: "Hainan" },
    { value: "cq", label: "Chongqing" },
    { value: "sc", label: "Sichuan" },
    { value: "gz", label: "Guizhou" },
    { value: "yn", label: "Yunnan" },
    { value: "xz", label: "Tibet" },
    { value: "sn", label: "Shaanxi" },
    { value: "gs", label: "Gansu" },
    { value: "qh", label: "Qinghai" },
    { value: "nx", label: "Ningxia" },
    { value: "xj", label: "Xinjiang" }
  ],
  ru: [
    { value: "alt", label: "Altai Krai" },
    { value: "amu", label: "Amur Oblast" },
    { value: "ark", label: "Arkhangelsk Oblast" },
    { value: "ast", label: "Astrakhan Oblast" },
    { value: "bel", label: "Belgorod Oblast" },
    { value: "bry", label: "Bryansk Oblast" },
    { value: "che", label: "Chelyabinsk Oblast" },
    { value: "chu", label: "Chukotka Autonomous Okrug" },
    { value: "irk", label: "Irkutsk Oblast" },
    { value: "iva", label: "Ivanovo Oblast" },
    { value: "kam", label: "Kamchatka Krai" },
    { value: "kgd", label: "Kaliningrad Oblast" },
    { value: "kha", label: "Khabarovsk Krai" },
    { value: "kir", label: "Kirov Oblast" },
    { value: "kos", label: "Kostroma Oblast" },
    { value: "kya", label: "Krasnoyarsk Krai" },
    { value: "len", label: "Leningrad Oblast" },
    { value: "lip", label: "Lipetsk Oblast" },
    { value: "mag", label: "Magadan Oblast" },
    { value: "mos", label: "Moscow Oblast" },
    { value: "mow", label: "Moscow" },
    { value: "mur", label: "Murmansk Oblast" },
    { value: "niz", label: "Nizhny Novgorod Oblast" },
    { value: "nov", label: "Novgorod Oblast" },
    { value: "nsk", label: "Novosibirsk Oblast" },
    { value: "oms", label: "Omsk Oblast" },
    { value: "ore", label: "Orenburg Oblast" },
    { value: "orl", label: "Oryol Oblast" },
    { value: "pnz", label: "Penza Oblast" },
    { value: "pri", label: "Primorsky Krai" },
    { value: "psk", label: "Pskov Oblast" },
    { value: "ros", label: "Rostov Oblast" },
    { value: "rya", label: "Ryazan Oblast" },
    { value: "sak", label: "Sakhalin Oblast" },
    { value: "sam", label: "Samara Oblast" },
    { value: "sar", label: "Saratov Oblast" },
    { value: "smo", label: "Smolensk Oblast" },
    { value: "spb", label: "Saint Petersburg" },
    { value: "sve", label: "Sverdlovsk Oblast" },
    { value: "tam", label: "Tambov Oblast" },
    { value: "tom", label: "Tomsk Oblast" },
    { value: "tul", label: "Tula Oblast" },
    { value: "tve", label: "Tver Oblast" },
    { value: "tyu", label: "Tyumen Oblast" },
    { value: "vla", label: "Vladimir Oblast" },
    { value: "vlg", label: "Volgograd Oblast" },
    { value: "vog", label: "Vologda Oblast" },
    { value: "vor", label: "Voronezh Oblast" },
    { value: "yar", label: "Yaroslavl Oblast" }
  ],
  sg: [
    { value: "cs", label: "Central Singapore" },
    { value: "es", label: "East Singapore" },
    { value: "ns", label: "North Singapore" },
    { value: "ne", label: "North-East Singapore" },
    { value: "ws", label: "West Singapore" }
  ],
  ae: [
    { value: "ad", label: "Abu Dhabi" },
    { value: "aj", label: "Ajman" },
    { value: "du", label: "Dubai" },
    { value: "fu", label: "Fujairah" },
    { value: "rk", label: "Ras Al Khaimah" },
    { value: "sh", label: "Sharjah" },
    { value: "uq", label: "Umm Al Quwain" }
  ],
  se: [
    { value: "sto", label: "Stockholm" },
    { value: "upp", label: "Uppsala" },
    { value: "sod", label: "Södermanland" },
    { value: "ost", label: "Östergötland" },
    { value: "jon", label: "Jönköping" },
    { value: "kro", label: "Kronoberg" },
    { value: "kal", label: "Kalmar" },
    { value: "got", label: "Gotland" },
    { value: "ble", label: "Blekinge" },
    { value: "ska", label: "Skåne" },
    { value: "hal", label: "Halland" },
    { value: "vgo", label: "Västra Götaland" },
    { value: "var", label: "Värmland" },
    { value: "ore", label: "Örebro" },
    { value: "vas", label: "Västmanland" },
    { value: "dal", label: "Dalarna" },
    { value: "gav", label: "Gävleborg" },
    { value: "vas", label: "Västernorrland" },
    { value: "jam", label: "Jämtland" },
    { value: "vbn", label: "Västerbotten" },
    { value: "nbn", label: "Norrbotten" }
  ]
} as const; 