image: node:20

definitions:
  caches:
    npm: ~/.npm
    next-cache: .next/cache

pipelines:
  branches:
    develop:
      - step:
          name: Install & Build
          caches:
            - npm
            - next-cache
          script:
            - node --version
            - npm --version
            - npm ci
            - echo "Building project..."
            - NEXT_TELEMETRY_DISABLED=1 npm run build -- --no-lint
            - echo "Exporting project..."
            - npm run export
          artifacts:
            - out/**
            - public/**
            - package*.json
            - next.config.js

      - step:
          name: Deploy to S3
          script:
            - npm ci
            - pipe: atlassian/aws-s3-deploy:0.3.8
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: hutjig-xuksi8-sYccek
                LOCAL_PATH: 'out'
                ACL: 'public-read'
                DELETE_FLAG: 'true'

    main:
      - step:
          name: Install & Build
          caches:
            - npm
            - next-cache
          script:
            - node --version
            - npm --version
            - npm ci
            - echo "Building project..."
            - NEXT_TELEMETRY_DISABLED=1 npm run build -- --no-lint
            - echo "Exporting project..."
            - npm run export
          artifacts:
            - out/**
            - public/**
            - package*.json
            - next.config.js

      - step:
          name: Deploy to Production
          deployment: production
          trigger: manual
          script:
            - npm ci
            - pipe: atlassian/aws-s3-deploy:0.3.8
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: hutjig-xuksi8-sYccek
                LOCAL_PATH: 'out'
                ACL: 'public-read'
                DELETE_FLAG: 'true' 