image: node:20

definitions:
  caches:
    npm: ~/.npm
    next-cache: .next/cache

pipelines:
  branches:
    develop:
      - step:
          name: Install & Build
          caches:
            - npm
            - next-cache
          script:
            - npm ci
            - npm run lint
            - npm run build
          artifacts:
            - .next/**
            - node_modules/**
            - public/**
            - package.json
            - package-lock.json
            - next.config.js

      - step:
          name: Deploy to Development
          deployment: development
          script:
            # Add your deployment commands here
            # Example for AWS EC2:
            # - pipe: atlassian/ssh-run:0.4.1
            #   variables:
            #     SSH_USER: $SSH_USER
            #     SERVER: $SERVER_IP
            #     COMMAND: 'cd /path/to/app && pm2 restart next-app'

    main:
      - step:
          name: Install & Build
          caches:
            - npm
            - next-cache
          script:
            - npm ci
            - npm run lint
            - npm run build
          artifacts:
            - .next/**
            - node_modules/**
            - public/**
            - package.json
            - package-lock.json
            - next.config.js

      - step:
          name: Deploy to Production
          deployment: production
          trigger: manual
          script:
            # Add your production deployment commands here 