export type Country = {
  value: string;
  label: string;
  flag: string;
}

export type State = {
  value: string;
  label: string;
}

export const countryCallingCodes: Record<string, string> = {
  "us": "1",
  "ca": "1",
  "gb": "44",
  "fr": "33",
  "de": "49",
  "it": "39",
  "es": "34",
  "au": "61",
  "nz": "64",
  "jp": "81",
  "kr": "82",
  "in": "91",
  "br": "55",
  "mx": "52",
  "za": "27",
  "cn": "86",
  "ru": "7",
  "sg": "65",
  "ae": "971",
  "se": "46"
}

export function getCountryCallingCode(countryCode: string): string {
  return countryCallingCodes[countryCode.toLowerCase()] || "1"
}

export const countries: Country[] = [
  { value: "us", label: "United States", flag: "/flags/US.svg" },
  { value: "ca", label: "Canada", flag: "/flags/CA.svg" },
  { value: "gb", label: "United Kingdom", flag: "/flags/GB.svg" },
  { value: "fr", label: "France", flag: "/flags/fr.svg" },
  { value: "de", label: "Germany", flag: "/flags/DE.svg" },
  { value: "it", label: "Italy", flag: "/flags/IT.svg" },
  { value: "es", label: "Spain", flag: "/flags/es.svg" },
  { value: "au", label: "Australia", flag: "/flags/AU.svg" },
  { value: "nz", label: "New Zealand", flag: "/flags/NZ.svg" },
  { value: "jp", label: "Japan", flag: "/flags/JP.svg" },
  { value: "kr", label: "South Korea", flag: "/flags/KR.svg" },
  { value: "in", label: "India", flag: "/flags/IN.svg" },
  { value: "br", label: "Brazil", flag: "/flags/BR.svg" },
  { value: "mx", label: "Mexico", flag: "/flags/MX.svg" },
  { value: "za", label: "South Africa", flag: "/flags/ZA.svg" },
  { value: "cn", label: "China", flag: "/flags/CN.svg" },
  { value: "ru", label: "Russia", flag: "/flags/RU.svg" },
  { value: "sg", label: "Singapore", flag: "/flags/SG.svg" },
  { value: "ae", label: "United Arab Emirates", flag: "/flags/AE.svg" },
  { value: "se", label: "Sweden", flag: "/flags/SE.svg" }
]

export const statesByCountry: Record<string, State[]> = {
  us: [
    { value: "al", label: "Alabama" },
    { value: "ak", label: "Alaska" },
    { value: "az", label: "Arizona" },
    { value: "ar", label: "Arkansas" },
    { value: "ca", label: "California" },
    { value: "co", label: "Colorado" },
    { value: "ct", label: "Connecticut" },
    { value: "de", label: "Delaware" },
    { value: "fl", label: "Florida" },
    { value: "ga", label: "Georgia" },
    { value: "hi", label: "Hawaii" },
    { value: "id", label: "Idaho" },
    { value: "il", label: "Illinois" },
    { value: "in", label: "Indiana" },
    { value: "ia", label: "Iowa" },
    { value: "ks", label: "Kansas" },
    { value: "ky", label: "Kentucky" },
    { value: "la", label: "Louisiana" },
    { value: "me", label: "Maine" },
    { value: "md", label: "Maryland" },
    { value: "ma", label: "Massachusetts" },
    { value: "mi", label: "Michigan" },
    { value: "mn", label: "Minnesota" },
    { value: "ms", label: "Mississippi" },
    { value: "mo", label: "Missouri" },
    { value: "mt", label: "Montana" },
    { value: "ne", label: "Nebraska" },
    { value: "nv", label: "Nevada" },
    { value: "nh", label: "New Hampshire" },
    { value: "nj", label: "New Jersey" },
    { value: "nm", label: "New Mexico" },
    { value: "ny", label: "New York" },
    { value: "nc", label: "North Carolina" },
    { value: "nd", label: "North Dakota" },
    { value: "oh", label: "Ohio" },
    { value: "ok", label: "Oklahoma" },
    { value: "or", label: "Oregon" },
    { value: "pa", label: "Pennsylvania" },
    { value: "ri", label: "Rhode Island" },
    { value: "sc", label: "South Carolina" },
    { value: "sd", label: "South Dakota" },
    { value: "tn", label: "Tennessee" },
    { value: "tx", label: "Texas" },
    { value: "ut", label: "Utah" },
    { value: "vt", label: "Vermont" },
    { value: "va", label: "Virginia" },
    { value: "wa", label: "Washington" },
    { value: "wv", label: "West Virginia" },
    { value: "wi", label: "Wisconsin" },
    { value: "wy", label: "Wyoming" }
  ],
  ca: [
    { value: "ab", label: "Alberta" },
    { value: "bc", label: "British Columbia" },
    { value: "mb", label: "Manitoba" },
    { value: "nb", label: "New Brunswick" },
    { value: "nl", label: "Newfoundland and Labrador" },
    { value: "ns", label: "Nova Scotia" },
    { value: "nt", label: "Northwest Territories" },
    { value: "nu", label: "Nunavut" },
    { value: "on", label: "Ontario" },
    { value: "pe", label: "Prince Edward Island" },
    { value: "qc", label: "Quebec" },
    { value: "sk", label: "Saskatchewan" },
    { value: "yt", label: "Yukon" }
  ],
  gb: [
    { value: "eng", label: "England" },
    { value: "sco", label: "Scotland" },
    { value: "wal", label: "Wales" },
    { value: "nir", label: "Northern Ireland" }
  ],
  fr: [
    { value: "als", label: "Alsace" },
    { value: "aqu", label: "Aquitaine" },
    { value: "bfc", label: "Brittany" },
    { value: "bre", label: "Bretagne" },
    { value: "cvl", label: "Centre-Val de Loire" },
    { value: "cor", label: "Corse" },
    { value: "hdf", label: "Hauts-de-France" },
    { value: "idf", label: "Île-de-France" },
    { value: "lrm", label: "Lorraine" },
    { value: "mrt", label: "Martinique" },
    { value: "ncr", label: "Nouvelle-Aquitaine" },
    { value: "norm", label: "Normandy" },
    { value: "pdl", label: "Pays de la Loire" },
    { value: "pdc", label: "Picardie" },
    { value: "pro", label: "Provence-Alpes-Côte d'Azur" },
    { value: "qcn", label: "Île de France" },
    { value: "rhone", label: "Rhône-Alpes" }
  ],
  de: [
    { value: "bw", label: "Baden-Württemberg" },
    { value: "by", label: "Bayern" },
    { value: "be", label: "Berlin" },
    { value: "bb", label: "Brandenburg" },
    { value: "hb", label: "Bremen" },
    { value: "hh", label: "Hamburg" },
    { value: "he", label: "Hessen" },
    { value: "mv", label: "Mecklenburg-Vorpommern" },
    { value: "ni", label: "Niedersachsen" },
    { value: "nw", label: "Nordrhein-Westfalen" },
    { value: "rp", label: "Rheinland-Pfalz" },
    { value: "sl", label: "Saarland" },
    { value: "sn", label: "Sachsen" },
    { value: "st", label: "Sachsen-Anhalt" },
    { value: "sh", label: "Schleswig-Holstein" },
    { value: "th", label: "Thüringen" }
  ],
  it: [
    { value: "ab", label: "Abruzzo" },
    { value: "ba", label: "Basilicata" },
    { value: "be", label: "Benevento" },
    { value: "bl", label: "Bologna" },
    { value: "bn", label: "Bolzano" },
    { value: "bs", label: "Brescia" },
    { value: "br", label: "Brindisi" },
    { value: "ca", label: "Cagliari" },
    { value: "fi", label: "Firenze" },
    { value: "ge", label: "Genova" },
    { value: "go", label: "Gorizia" },
    { value: "la", label: "La Spezia" },
    { value: "lc", label: "Lecco" },
    { value: "lo", label: "Lodi" },
    { value: "lu", label: "Lucca" },
    { value: "mn", label: "Mantova" },
    { value: "ms", label: "Massa" },
    { value: "mt", label: "Matera" },
    { value: "na", label: "Napoli" },
    { value: "no", label: "Novara" },
    { value: "or", label: "Oristano" },
    { value: "pa", label: "Palermo" },
    { value: "pr", label: "Parma" },
    { value: "pv", label: "Pavia" },
    { value: "pg", label: "Perugia" },
    { value: "pu", label: "Pesaro" },
    { value: "pe", label: "Pescara" },
    { value: "pn", label: "Pisa" },
    { value: "po", label: "Prato" },
    { value: "rg", label: "Ragusa" },
    { value: "ra", label: "Ravenna" },
    { value: "rc", label: "Reggio Calabria" },
    { value: "re", label: "Reggio Emilia" },
    { value: "ri", label: "Rieti" },
    { value: "ro", label: "Roma" },
    { value: "sa", label: "Salerno" },
    { value: "si", label: "Siena" },
    { value: "sr", label: "Siracusa" },
    { value: "so", label: "Sondrio" },
    { value: "ta", label: "Taranto" },
    { value: "te", label: "Teramo" },
    { value: "tr", label: "Trento" },
    { value: "ts", label: "Trieste" },
    { value: "tv", label: "Treviso" },
    { value: "ud", label: "Udine" },
    { value: "va", label: "Varese" },
    { value: "ve", label: "Venezia" },
    { value: "vb", label: "Verbano-Cusio-Ossola" },
    { value: "vi", label: "Vicenza" },
    { value: "vr", label: "Verona" }
  ],
  es: [
    { value: "ba", label: "Badajoz" },
    { value: "ib", label: "Islas Baleares" },
    { value: "le", label: "León" },
    { value: "lo", label: "La Rioja" },
    { value: "ma", label: "Málaga" }
  ]
} 